### ISSUE TITLE
...private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')

### ISSUE THREAD

**Issue by mikedad** [chef/chef-vault#259]
I have a working chef server running on Ubunto 16.04LTS.  Here’s the chef –version from the (windows) workstation:
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
berks version: 5.2.0
kitchen version: 1.14.2

I created a vault using this command (the user name is chefadmin, the node name is titan3):
```
knife vault create titan_cert_vault pfx_password_secret -A chefadmin -M client -S 'name:titan3' '{"password":"thesecret"}'
```

It worked, and the recipe that uses this item worked without issue.  I reset the key for chefadmin, and then started getting this error:
```
================================================================================
Recipe Compile Error in c:/chef/cache/cookbooks/websites_titan/recipes/webcert_prod.rb
================================================================================
ChefVault::Exceptions::SecretDecryption
---------------------------------------
titan_cert_vault/pfx_password_secret is encrypted for you, but your private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')
```
To try and fix this issue, as the error suggests, I tried to refresh the keys, yet, when I run the chef recipe, I still get the above error.

After a couple of hours trying refresh, update, rotate keys, etc.  I decided to create a new admin user, and a brand new vault, and created new keys for the titan3 server.  Then retried the vault refresh, update rotate keys, each time getting the above mentioned error.

Does anyone have any suggestions for what I might be missing?
Many thanks,
Mike

**Comment by esterp** [comment]
did you find a solution for this issue?  (I'm experiencing exactly the same thing)

**Comment by mikedad** [comment]
Unfortunately, I have not found an easy solution.  The rotate keys and refresh commands do not seem to work.  The only thing that has worked is to delete the vault and create a new one with the same name and the new values.

**Comment by esterp** [comment]
interesting, did "sudo knife vault edit ..." works for you?

**Comment by sanditiffin** [comment]
I was getting an error on any knife vault rotate command in all the 1.2.x-1.4.x versions of chefdk (didn't try earlier versions), but found a workaround.

$ knife vault rotate all keys
Rotating keys for: user_password bobo
ERROR: Chef::EncryptedDataBagItem::DecryptionFailure: Error decrypting data bag value: 'bad decrypt'. Most likely the provided key is incorrect.

I commented out the call to 'reload_raw_data' in the 'rotate_keys!' method on line 179 of /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-vault-2.9.1/lib/chef-vault/item.rb, it appears to work .. keys are rotated, and I can decrypt them after rotation using 'knife vault show VAULT ITEM'.

**Comment by sanditiffin** [comment]
@coderanger

**Comment by kamaradclimber** [comment]
@mikedad which version of chef-vault are you using?

To solve your issue, I would recommend trying the following steps:
- `knife data bag edit titan_cert_vault pfx_password_secret_keys`
-  remove any mention to chefadmin user (they are two: one in admin/client section, one where `chefadmin` is the key associated with a base64 value)
- quit the editor
- refresh the secrets (if chefadmin is a node) or update it (if chefadmin is a user)

Recent version of chef-vault ( >=3.0.1) might have difficulty to cope with user/client key change.

Let me know if it fixes your issue.

**Comment by perlun** [comment]
I seem to have seen similar issues with recent versions of chef-vault:

- `knife vault refresh docker-hub credentials` with new version, did not work.
- Downgraded chef-vault
- `knife vault refresh docker-hub` _did_ work.

Is it a big difference if you refresh the vault or the vault item? As that can also have been the cause here.

**Comment by kamaradclimber** [comment]
This issue is likely solved in chef-vault 3.3.0 since we've disabled the optimization on refresh related to that behavior.

**Comment by SrikarshVardhanreddyKolanu** [comment]
@kamaradclimber no we are still experiencing this issue 

```ERROR: keys/edh-preprod_chefadmin_keytab is encrypted for you, but your private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')
chef gem list chef-vault

*** LOCAL GEMS ***

chef-vault (3.3.0)
gem list chef-vault

*** LOCAL GEMS ***

chef-vault (3.4.0)
 chef -v
Chef Development Kit Version: 0.16.28
chef-client version: 13.7.16
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
knberks version: 4.3.5
ife kitchen version: 1.10.2
knife -v
Chef: 13.7.16

**Comment by kamaradclimber** [comment]
@SrikarshVardhanreddyKolanu the original root cause has been fixed. I believe you have the same error for different reasons. Could you give details on the scenario you are following to get this error?

**Comment by SrikarshVardhanreddyKolanu** [comment]
@kamaradclimber hey I tried to create a new chef server and ran the same after uploading a data bag item using vault
knife vault create DATA_BAG DATA_BAG_ITEM -J File.json -S "role:base" -M "client" -C "client01" -A "admin"

first it was showing
ERROR: undefined method `unpack' for nil:NilClass pointing towards one of the data bag item.

Then I updated the data bag item using vault then I got below error

knife vault update DATA_BAG DATA_BAG_ITEM -J File.json -S "role:base" -M "client" -C "client01" -A "admin"
ERROR: DATA_BAG/DATA_BAG_ITEM is encrypted for you, but your private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')

Could you please suggest what mistake I did ?

**Comment by SrikarshVardhanreddyKolanu** [comment]
@kamaradclimber Do I need to raise a separate issue for this ?

**Comment by neaGaze** [comment]
I'm facing the exact issue too. Is there any update of this?

**Comment by ejiec004** [comment]
Hi 

I am experiencing the same issue here, I tried to reset my keys and ran knife vault refresh after that, but still getting the same error. Can anyone please suggest?

`PS C:\abhi\devcernermain\chef-starter\chef-repo\data_bags> knife vault show databag databagsecrets -Fjson -p all
ERROR: ChefVault::Exceptions::SecretDecryption: databag/databagsecrets is encrypted for you, but your private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')`
