### ISSUE TITLE
vault? method should throw meaningful exception when no data bag exists

### ISSUE THREAD

**Issue by mhedgpeth** [chef/chef-vault#278]
Steps to reproduce:

1) in a cookbook call [chef_vault_item](https://github.com/chef-cookbooks/chef-vault/blob/master/libraries/helpers.rb#L37) method
2) this will check if the data bag is a vault with the ChefItem::vault? method
3) make sure that there isn't any data bag with that name.

Expected results:
* Exception is thrown saying "data bag X item Y does not exist" when 404 is returned back

Actual result:
This is the error, which is confusing and requires investigation to understand:

```
Net::HTTPServerException
------------------------
404 "Object Not Found"
Cookbook Trace:
---------------
  d:/chef/cache/cookbooks/chef-vault/libraries/helpers.rb:36:in `chef_vault_item'
  d:/chef/cache/cookbooks/ncr-cloudpassage/recipes/default.rb:9:in `from_file'
  d:/chef/cache/cookbooks/ncr-security/recipes/default.rb:7:in `from_file'
```

**Comment by mhedgpeth** [comment]
I'm on version 2.9.0 which might be the problem. I'm going to upgrade and do some more investigation. Will submit a PR for a fix or close this issue if it's not a real issue for the current branch.

**Comment by mhedgpeth** [comment]
I confirm that on the latest 3.0.3 version I still get a confusing error. I also get other error noise as well:

```
[2017-06-02T16:23:54-05:00] INFO: Using cafe with chef
[2017-06-02T16:23:54-05:00] INFO: Expecting cafe to run on platform: win8
[2017-06-02T16:23:55-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:55-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:55-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:55-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:56-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:56-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:56-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:56-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item artifactory_cred
entials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:57-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item signing_certificate_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:57-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item signing_certific
ate_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:57-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item signing_certificate_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:58-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item signing_certificate_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:58-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:58-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:59-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:59-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:23:59-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:00-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:00-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:00-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_service_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:01-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_app_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:01-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_app_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:02-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_app_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:02-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item legacy_app_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:02-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item sql_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:03-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item sql_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:03-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item sql_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:03-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item sql_credentials_key_labmynode01 for data bag myproduct
[2017-06-02T16:24:03-05:00] INFO: HTTP Request Returned 404 Object Not Found: error

  ================================================================================
  Recipe Compile Error in D:/chef/cache/cookbooks/ncr-security/recipes/default.rb
  ================================================================================

  Net::HTTPServerException
  ------------------------
  404 "Object Not Found"

  Cookbook Trace:
  ---------------
    D:/chef/cache/cookbooks/chef-vault/libraries/helpers.rb:36:in `chef_vault_item'
```

**Comment by kamaradclimber** [comment]
Hello @mhedgpeth,

a more meaningful error would be nice indeed. You have to take care of not breaking the interface for users that might rely on the exception type to do adapt their behavior (I'm thinking of chef-secrets cookbook for instance).

Feel free to start a PR so we can discuss the implementation.

**Comment by infinityminglei** [comment]
I am experiencing the same error noises too like following:
[2017-07-03 15:44:09 +0000] [info] [pid=17482] [tid=70213126844320] [context=dev job=deploy]: STDOUT: [2017-07-03T10:44:09-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item oauth_config_key_node1 for data bag vault_dev
[2017-07-03 15:44:09 +0000] [info] [pid=17482] [tid=70213126844320] [context=dev job=deploy]: STDOUT: [2017-07-03T10:44:09-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item oauth_config_key_node1 for data bag vault_dev
[2017-07-03 15:44:10 +0000] [info] [pid=17482] [tid=70213126844320] [context=dev job=deploy]: STDOUT: [2017-07-03T10:44:10-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item oauth_config_key_node1 for data bag empi_acdc_vault_dev
[2017-07-03 15:44:10 +0000] [info] [pid=17482] [tid=70213126844320] [context=dev job=deploy]: STDOUT: [2017-07-03T10:44:10-05:00] INFO: HTTP Request Returned 404 Object Not Found: Cannot load data bag item oauth_config_key_node1 for data bag vault_dev

Why does it try to check nonexistent data bag items? I only have oauth_config_key data bags in the vault and why does it try to check the data bag item which have a node name prefixed?

**Comment by kamaradclimber** [comment]
Next version of chef valut (3.2.0) should fix this issue since it has been fixed already in mastzr branch

**Comment by kamaradclimber** [comment]
@mhedgpeth have you been able to submit a PR to fix the original issue?
The side issue (additional noise) has been fixed in 3.2.0.

**Comment by saidmasoud** [comment]
I am having the same issue @Poohblah mentioned above; however, adding `data_bags_path` to Kitchen did not resolve the issue. I am using `chef-vault` 3.3.0 and `chef-vault-testfixtures` 3.0.1.
